ARG GO_IMAGE
ARG ALPINE_IMAGE

FROM ${GO_IMAGE} AS builder

ARG ALPINE_IMAGE
ARG TARGETARCH

ARG WORKDIR
WORKDIR ${WORKDIR}

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} \
    go build -ldflags="-w -s" -o main ./cmd/http_db_update_server

FROM ${ALPINE_IMAGE}

RUN addgroup -g 1000 appgroup && \
    adduser -u 1000 -G appgroup -D appuser

RUN apk --no-cache add ca-certificates

ARG WORKDIR
WORKDIR ${WORKDIR}
RUN chown -R appuser:appgroup ${WORKDIR}

COPY --from=builder /app/main .
RUN chown -R appuser:appgroup ${WORKDIR}

USER appuser

CMD ["./main"]
