ARG GO_VERSION=1.25.6
ARG ALPINE_VERSION=3.23

FROM --platform=${BUILDPLATFORM} golang:${GO_VERSION}-alpine${ALPINE_VERSION} AS builder

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG TARGETOS
ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=${TARGETOS} GOARCH=${TARGETARCH} \
    go build -ldflags="-w -s" -o main ./cmd/http_db_update_server/main.go

FROM alpine:${ALPINE_VERSION}

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN apk --no-cache add ca-certificates

WORKDIR /home/appuser

COPY --from=builder /app/main .

USER appuser

CMD ["./main"]
