FROM --platform=${BUILDPLATFORM} golang:1.23 as builder

LABEL maintainer="Adam Hofman <adam.hofman1@gmail.com>"

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/http-db-update-server ./cmd/http-db-update-server
COPY ./internal ./internal

ARG TARGETARCH

RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH:-amd64} go build -a -installsuffix cgo -o main ./cmd/http-db-update-server/main.go

FROM --platform=${BUILDPLATFORM} alpine:3.20

WORKDIR /root/

COPY --from=builder /app/main .

CMD ["./main"]