version: '3'
services:
  http_database_update_server:
    restart: "on-failure"
    build:
      context: .
      dockerfile: ./http-database-update-server/Dockerfile
    platform: linux/arm64
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file: env.list
    volumes:
      - shared_data:/tmp
    networks:
      - MOB_network
  db:
    restart: "on-failure"
    image: postgres:14.7
    command: -c ssl=off
    env_file: env.list
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - shared_data:/tmp
    networks:
      - MOB_network
  mosquitto:
    restart: "on-failure"
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
    volumes:
      - mosquitto_config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
      - ./mosquitto-config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - MOB_network
  mqtt_database_api:
    restart: "on-failure"
    build:
      context: .
      dockerfile: ./mqtt-database-api/Dockerfile
    platform: linux/arm64
    depends_on:
      - db
      - mosquitto
    networks:
      - MOB_network
    env_file: env.list
volumes:
  postgres_data:
  shared_data:
  mosquitto_config:
  mosquitto_data:
  mosquitto_log:
networks:
  MOB_network:
