ARG GO_IMAGE

FROM ${GO_IMAGE} AS builder

ARG ALPINE_IMAGE
ARG TARGETARCH
ARG WORKDIR

WORKDIR ${WORKDIR}

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} \
    go build -ldflags="-w -s" -o main ./cmd/cli_control_app

FROM ${ALPINE_IMAGE}

RUN apk --no-cache add ca-certificates bash mdbtools

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

ARG WORKDIR
WORKDIR ${WORKDIR}

COPY --from=builder /app/main .
COPY --from=builder /app/cmd/cli_control_app/mdb_to_csv.sh .
RUN chmod +x ./mdb_to_csv.sh

USER appuser

CMD ["./main"]
