ARG GO_IMAGE

FROM ${GO_IMAGE} AS builder

ARG GO_IMAGE
ARG ALPINE_IMAGE
ARG TARGETARCH

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=${TARGETARCH} \
    go build -ldflags="-w -s" -o main ./cmd/cli_control_app

FROM ${ALPINE_IMAGE}

ARG ALPINE_IMAGE

RUN addgroup -S appgroup && adduser -S appuser -G appgroup

RUN apk --no-cache add ca-certificates

WORKDIR /home/appuser

COPY --from=builder /app/main .

USER appuser

CMD ["./main"]
